// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StaffManagement.Data;

#nullable disable

namespace StaffManagement.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StaffManagement.Models.Staff", b =>
                {
                    b.Property<string>("StaffId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.HasKey("StaffId");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            StaffId = "SF00001",
                            Birthday = new DateOnly(2000, 1, 1),
                            FullName = "Staff 1",
                            Gender = 1
                        },
                        new
                        {
                            StaffId = "SF00002",
                            Birthday = new DateOnly(1995, 5, 30),
                            FullName = "Staff 2",
                            Gender = 2
                        },
                        new
                        {
                            StaffId = "SF00003",
                            Birthday = new DateOnly(1999, 2, 15),
                            FullName = "Staff 3",
                            Gender = 1
                        },
                        new
                        {
                            StaffId = "SF00004",
                            Birthday = new DateOnly(2001, 1, 25),
                            FullName = "Staff 4",
                            Gender = 1
                        },
                        new
                        {
                            StaffId = "SF00005",
                            Birthday = new DateOnly(2001, 1, 25),
                            FullName = "Staff 5",
                            Gender = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
